//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TryitPage.Register {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Register.IRegister")]
    public interface IRegister {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegister/firstName", ReplyAction="http://tempuri.org/IRegister/firstNameResponse")]
        string firstName(string fName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegister/firstName", ReplyAction="http://tempuri.org/IRegister/firstNameResponse")]
        System.Threading.Tasks.Task<string> firstNameAsync(string fName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegister/lastName", ReplyAction="http://tempuri.org/IRegister/lastNameResponse")]
        string lastName(string lName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegister/lastName", ReplyAction="http://tempuri.org/IRegister/lastNameResponse")]
        System.Threading.Tasks.Task<string> lastNameAsync(string lName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegister/gradHs", ReplyAction="http://tempuri.org/IRegister/gradHsResponse")]
        string gradHs(string f, string l, string yesOrno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegister/gradHs", ReplyAction="http://tempuri.org/IRegister/gradHsResponse")]
        System.Threading.Tasks.Task<string> gradHsAsync(string f, string l, string yesOrno);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRegisterChannel : TryitPage.Register.IRegister, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RegisterClient : System.ServiceModel.ClientBase<TryitPage.Register.IRegister>, TryitPage.Register.IRegister {
        
        public RegisterClient() {
        }
        
        public RegisterClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RegisterClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RegisterClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RegisterClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string firstName(string fName) {
            return base.Channel.firstName(fName);
        }
        
        public System.Threading.Tasks.Task<string> firstNameAsync(string fName) {
            return base.Channel.firstNameAsync(fName);
        }
        
        public string lastName(string lName) {
            return base.Channel.lastName(lName);
        }
        
        public System.Threading.Tasks.Task<string> lastNameAsync(string lName) {
            return base.Channel.lastNameAsync(lName);
        }
        
        public string gradHs(string f, string l, string yesOrno) {
            return base.Channel.gradHs(f, l, yesOrno);
        }
        
        public System.Threading.Tasks.Task<string> gradHsAsync(string f, string l, string yesOrno) {
            return base.Channel.gradHsAsync(f, l, yesOrno);
        }
    }
}
