//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TryitPage.Enroll {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Enroll.IEnroll")]
    public interface IEnroll {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEnroll/emailOrID", ReplyAction="http://tempuri.org/IEnroll/emailOrIDResponse")]
        string emailOrID(string enroll);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEnroll/emailOrID", ReplyAction="http://tempuri.org/IEnroll/emailOrIDResponse")]
        System.Threading.Tasks.Task<string> emailOrIDAsync(string enroll);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEnroll/totalUnits", ReplyAction="http://tempuri.org/IEnroll/totalUnitsResponse")]
        void totalUnits(int u);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEnroll/totalUnits", ReplyAction="http://tempuri.org/IEnroll/totalUnitsResponse")]
        System.Threading.Tasks.Task totalUnitsAsync(int u);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEnrollChannel : TryitPage.Enroll.IEnroll, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EnrollClient : System.ServiceModel.ClientBase<TryitPage.Enroll.IEnroll>, TryitPage.Enroll.IEnroll {
        
        public EnrollClient() {
        }
        
        public EnrollClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EnrollClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EnrollClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EnrollClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string emailOrID(string enroll) {
            return base.Channel.emailOrID(enroll);
        }
        
        public System.Threading.Tasks.Task<string> emailOrIDAsync(string enroll) {
            return base.Channel.emailOrIDAsync(enroll);
        }
        
        public void totalUnits(int u) {
            base.Channel.totalUnits(u);
        }
        
        public System.Threading.Tasks.Task totalUnitsAsync(int u) {
            return base.Channel.totalUnitsAsync(u);
        }
    }
}
